[versions]
kotlin = "2.4.20-Beta1"

paper = "26.3-rc-3.build.1-alpha"
minecraft = "26.2"

run-task = "3.0.2"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

[plugins]
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-task" }
